{
 "title": "APLICAÇÕES VIVO",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "RedeL",
    "query": {}
   },
   {
    "name": "TipoLC",
    "query": {}
   },
   {
    "name": "TipoLD",
    "query": {}
   },
   {
    "name": "Rede",
    "query": {}
   },
   {
    "name": "Tipo",
    "label": "Tipo de Trafego",
    "query": {}
   },
   {
    "name": "Host",
    "query": {}
   },
   {
    "name": "RedeH",
    "query": {}
   },
   {
    "name": "RedeR",
    "query": {}
   },
   {
    "name": "TipoCNx",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "VIVO SIP HUB", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# THE" } },
  { "title": "$Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }, "repeat": "Host" },
  {
   "title": "ICMP Response time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "application": { "filter": "Status" },
     "group": { "filter": "$Tipo" },
     "host": { "filter": "$Host" },
     "item": { "filter": "ICMP response time" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 11, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Status" },
     "group": { "filter": "$Tipo" },
     "host": { "filter": "$Host" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ICMP Loss",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 2 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "Status" },
     "group": { "filter": "$Tipo" },
     "host": { "filter": "$Host" },
     "item": { "filter": "ICMP loss" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}