{
 "title": "BANCO CSF - ATENTO - HOSTFIBER",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Available -Atento - Hostfiber",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "$$hashKey": "object:1175",
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "bottom",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "1",
        "count"
       ],
       "text": "bottom(1, count)"
      }
     ],
     "group": { "filter": "HOSTFIBER" },
     "host": {
      "filter": "BANCO CSF - ATENTO - 2951 - HOSTFIBER"
     },
     "item": { "filter": "ICMP ping" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 9, "y": 0 },
   "repeat": "Hosts",
   "options": {
    "content": "<div class=\"text-center dashboard-header\"><strong><em>BANCO CSF - CARREFOUR</em></strong></div>\n"
   }
  },
  {
   "title": "Available -Atento 2  - Hostfiber",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "$$hashKey": "object:1202",
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "bottom",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "1",
        "count"
       ],
       "text": "bottom(1, count)"
      }
     ],
     "group": { "filter": "HOSTFIBER" },
     "host": {
      "filter": "BANCO CSF - ATENTO 2 - 2911 - HOSTFIBER"
     },
     "item": { "filter": "ICMP ping" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ATENTO - HOSTFIBER - CONSUMO DE BANDA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "application": { "filter": "Network Interfaces" },
     "group": { "filter": "HOSTFIBER" },
     "host": {
      "filter": "BANCO CSF - ATENTO - 2951 - HOSTFIBER"
     },
     "item": {
      "filter": "Interface Gi0/1(LINK_HOSTFIBER): Bits received"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Network Interfaces" },
     "group": { "filter": "HOSTFIBER" },
     "host": {
      "filter": "BANCO CSF - ATENTO - 2951 - HOSTFIBER"
     },
     "item": {
      "filter": "Interface Gi0/1(LINK_HOSTFIBER): Bits sent"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ATENTO 2 - HOSTFIBER - CONSUMO DE BANDA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "application": { "filter": "Network Interfaces" },
     "group": { "filter": "HOSTFIBER" },
     "host": {
      "filter": "BANCO CSF - ATENTO 2 - 2911 - HOSTFIBER"
     },
     "item": {
      "filter": "Interface Gi0/0(ALGAR): Bits received"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Network Interfaces" },
     "group": { "filter": "HOSTFIBER" },
     "host": {
      "filter": "BANCO CSF - ATENTO 2 - 2911 - HOSTFIBER"
     },
     "item": {
      "filter": "Interface Gi0/0(ALGAR): Bits sent"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}