{
 "title": "STATUS 5G VISION",
 "description": "Dashboard com: Alerta de Incidentes, Espaço em Disco, CPU, Temperatura e Algumas informações do Zabbix Server.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "Hosts",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Utilization",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/(.*) Memory utilization/",
        "$1"
       ],
       "text": "replaceAlias(/(.*) Memory utilization/, $1)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "/Memory utilization/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU utilization $Hosts",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "functions": [
      {
       "$$hashKey": "object:1863",
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "5",
        "avg"
       ],
       "text": "top(5, avg)"
      },
      {
       "$$hashKey": "object:1864",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "CPU" ],
       "text": "setAlias(CPU)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "/CPU utilization/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Storage Server - / $Hosts",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Storage" },
     "functions": [
      {
       "$$hashKey": "object:1806",
       "added": false,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Total" ],
       "text": "setAlias(Total)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "/: Total space" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Storage" },
     "functions": [
      {
       "$$hashKey": "object:1808",
       "added": false,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Used" ],
       "text": "setAlias(Used)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "/: Used space" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total memory",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "/Total memory/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Used memory",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "/Used memory/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU $Hosts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "/CPU (?!idle)/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ALERTA DE INCIDENTES",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 9 },
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "" },
     "options": {
      "acknowledged": 2,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 0,
      "severities": [
       0,
       1,
       2,
       3,
       4,
       5
      ],
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "lastchange"
     },
     "proxy": { "filter": "" },
     "showProblems": "recent",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}